import React from "react";

export default function Logo() {
  return (
    <div>
      <svg
        width="36"
        height="36"
        viewBox="0 0 40 40"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        className="inline-block align-middle"
      >
        <circle
          cx="9"
          cy="28"
          r="7"
          stroke="white"
          strokeWidth="2"
          fill="none"
        />
        <circle
          cx="31"
          cy="28"
          r="7"
          stroke="white"
          strokeWidth="2"
          fill="none"
        />
        <line
          x1="9"
          y1="28"
          x2="20"
          y2="14"
          stroke="white"
          strokeWidth="2"
          strokeLinecap="round"
        />
        <line
          x1="20"
          y1="14"
          x2="31"
          y2="28"
          stroke="white"
          strokeWidth="2"
          strokeLinecap="round"
        />
        <line
          x1="20"
          y1="14"
          x2="24"
          y2="28"
          stroke="white"
          strokeWidth="2"
          strokeLinecap="round"
        />
        <line
          x1="18"
          y1="14"
          x2="26"
          y2="14"
          stroke="white"
          strokeWidth="2"
          strokeLinecap="round"
        />
        <line
          x1="26"
          y1="14"
          x2="28"
          y2="11"
          stroke="white"
          strokeWidth="2"
          strokeLinecap="round"
        />
        <line
          x1="16"
          y1="14"
          x2="14"
          y2="11"
          stroke="white"
          strokeWidth="2"
          strokeLinecap="round"
        />
        <line
          x1="12"
          y1="11"
          x2="16"
          y2="11"
          stroke="white"
          strokeWidth="2.5"
          strokeLinecap="round"
        />
      </svg>
    </div>
  );
}
